//! Calltracks Web Number Dynamics - 3rd generation - Copyright 2007 onwards, Calltracks, pd
//! This code is generated by the Calltracks system
function providePlugin(pluginName, pluginConstructor) {
  var gac = typeof(ga) == "function" ? ga : window[window['GoogleAnalyticsObject']];
  if (gac) gac('provide', pluginName, pluginConstructor);
}
var CTPlugin = function(tracker, config) {
  this.tracker = tracker;
  session_id = 59208019;
  sid_index = config.slotNum;
  this.tracker.set('dimension'+sid_index, session_id);
  if(config.cid_slotNum) {
    this.tracker.set('dimension'+config.cid_slotNum, tracker.get('clientId'));
  }
};
providePlugin('ctplugin', CTPlugin);

if (typeof(dataLayer) !== "undefined") {
  if (dataLayer) {
    dataLayer.push({ 'event': 'visitIdSet', 'visitId': '59208019' });
  }
}

var _ctq = _ctq || [];
var __ctg3 = (function(ctWindow){
  var unknownIdentifiers = {};

  var ua_client_id = '';
  var log_pingback = function(interval){
    var o=document.getElementById('ct_pingback');if(o){o.parentNode.removeChild(o)}
    var ua_params = '';

    function getClientIdFromCookie() {
      try {
        var cookie = document.cookie.match(new RegExp('_ga=([^;]+)'))[1].split('.');
        return cookie[2] + '.' + cookie[3];
      } catch (e) {
        return '';
      }
    }

    function pingbackAndSchedule(ua_params) {
      if (interval < 1800000) { interval = parseInt(interval * 1.1, 10); }
      var wnd_pv_scr = document.createElement('script');
      src_string = 'https://pendragon.calltracks.com:443/wnd/pingback.js?pid=325813156&int=' + interval + '&fk=' + encodeURIComponent(__ctwnd.rc('__utma')) + '&c=' + encodeURIComponent(__ctwnd.rc('__utmz')) + '&cv=' + encodeURIComponent(__ctwnd.rc('__utmv')) + ua_params  ;
      wnd_pv_scr.setAttribute('src', src_string);
      wnd_pv_scr.setAttribute('type', 'text/javascript');
      wnd_pv_scr.setAttribute('id', 'ct_pingback');
      document.getElementsByTagName('head')[0].appendChild(wnd_pv_scr);
      var to = ctWindow.setTimeout(function() { log_pingback(interval) }, interval);
    }

    var gac = window[window['GoogleAnalyticsObject'] || 'ga'];
    if(typeof(gac) == "function") {
      gac(function(tracker){
        if (!tracker) {
          tracker = gac.getAll()[0];
        }
        if (!tracker) {
          if (window.ga && window.ga.getAll && window.ga.getAll()) {
            tracker = window.ga.getAll()[0];
          }
        }

        if (tracker) {
          ua_client_id = tracker.get('clientId');
        }

        if (!ua_client_id) {
          ua_client_id = getClientIdFromCookie();
        }

        if (ua_client_id) {
          ua_params = ua_params + '&ua_client_id=' + ua_client_id;
        }

        pingbackAndSchedule(ua_params);
      });
    } else {
      pingbackAndSchedule(ua_params);
    }
  };

  var getElementsByClassName = function(strClassName) {

    if (document.querySelectorAll) {
      foundElements = document.querySelectorAll("[class*=calltracks_]");
      var arrElements = Array.prototype.slice.call(foundElements);
    } else {
      var arrElements = [];
    }

    var arrReturnElements = [];
    for(var i=0; i<arrElements.length; i++){ var classes=arrElements[i].className.split(' '); for (var j=0;j<classes.length;j++){ if(classes[j].toLowerCase() == strClassName.toLowerCase()){arrReturnElements.push(arrElements[i])} } }
    return arrReturnElements;
  };
  var replaceNumber = function(identifierName,custom_formatted,unformatted,intl) {
    var elements = getElementsByClassName(identifierName);
    for (var i = elements.length - 1; i >= 0; i--) {
      var e=elements[i];
      if(e.getAttribute("data-calltracks-no-replace") == null){ if(!e.getAttribute('data-orig-innerhtml')){e.setAttribute('data-calltracks-orig-innerhtml', encodeURIComponent(e.innerHTML))};e.innerHTML = custom_formatted;e.setAttribute('data-calltracks-replaced-at',new Date().getTime())}
        if(e.tagName=="A" && e.href.indexOf("tel:")==0){
          e.href = "tel:" + unformatted;
        }
      if(e.parentNode.tagName=="A" && e.parentNode.href.indexOf("tel:")==0){
        e.parentNode.href = "tel:" + intl;
      }
      if(__ctg3.unhide!==false){e.style.display=__ctg3.unhide}

      var elementClasses = e.className.split(' ');
      for(var j = 0; j < elementClasses.length; j++) {
        var identifier = elementClasses[j].replace(/^calltracks_/, '').toLowerCase();
        delete unknownIdentifiers[identifier];
      }
    }
  };

  return {
    unhide: false,
    run: function(){
      for (var i=0;i<_ctq.length;i++){var o=_ctq[i];if(o[0]==="_unhide"){__ctg3.unhide=o[1]}}
        replaceNumber("calltracks_03333237257", '0344 659 4962', '03446594962', '+443446594962' );
        __ctwnd.sc(__ctwnd.infoCookieName(), 'kwid%3D%3Brefid%3D%3Bvid%3D59208019');
        var to = ctWindow.setTimeout(function() { log_pingback(20000) }, 3000);
      if (__ctwnd.needReInit){__ctwnd.needReInit=false;__ctwnd.reinit();}
      if (Object.keys && Object.keys(unknownIdentifiers).length > 0) {
        if(console) {
          console.log("Errors reported by Calltracks: Unknown identifiers on page (not set up in Calltracks, or currently disabled): " + Object.keys(unknownIdentifiers));
        }
      }


    },
    getPid: function(){
      return 325813156;
    }
  };
})(window);

__ctg3.run();
